apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: fitcheck
type: Opaque
stringData:
  POSTGRES_USER: fituser
  POSTGRES_PASSWORD: fitpass
  POSTGRES_DB: fitcheck
  DATABASE_URL: postgresql://fituser:fitpass@postgres:5432/fitcheck
